### ISSUE TITLE
Enhancement. Fire `closeWithGrace` callback even if process closing in normal way.

### ISSUE THREAD

**Issue by Sadzurami** [mcollina/close-with-grace#15]
When process closes in normal way (without errors or signals), callback of closeWithGrace not calling automatically.
The only way to fire callback is calling method `close()` that `closeWithGrace()` returns after installing listeners.

Example:
```js
const { close } = closeWithGrace(() => somethingUseful());
process.on('beforeExit', () => close());
```

Pros:
Only one callback for entire app that makes useful things before exit. No need to create another handlers.

Will be cool to add 'beforeExit' handler to closeWithGrace listeners.
I can make PR, if you think thats suits for lib.

**Comment by mcollina** [comment]
released in v2.0.0
