### ISSUE TITLE
Fastify server doesn't close properly

### ISSUE THREAD

**Issue by Danielg212** [mcollina/close-with-grace#25]
I have below code,

```typescript

const bootstrap = async () => {

  const app = await buildServer();
  app.listen({ port: PORT,host:HOST }, (err, address) => {
    if (err) {
      console.error(err);
      process.exit(1);
    }
    console.log(`Server is runnin on ${address}`);
  });

  closeWithGrace({delay:2000},async ({err,signal})=>{
    console.log('Shutting down server gracefully...👑');
    console.log(err,signal);
   await app.close();
  })
};

```
When CTRL+C is pressed, the server sometimes waits and close "gracefully" and sometimes doesn't.

I'm starting the server with `  "start": "tsx watch server/index.ts"`, image attached below for reference. 

<img width="541" alt="image" src="https://github.com/user-attachments/assets/9a297788-0d87-4bd0-a3ae-e84fdeff67c2">

**Comment by mcollina** [comment]
This is to be expected, it really depends on your application and what kind of clients are connected. You should really report this to Fastify, as it's not relevant to this repo at all.
