### ISSUE TITLE
Fastify server doesn't close properly

### ISSUE THREAD

**Issue by sujeet-agrahari** [mcollina/close-with-grace#8]
I have below code,
```
const closeListeners = closeWithGrace(
  { delay: 500 },
  async ({ signal, err }) => {
    if (err) {
      app.log.error({ err }, 'server closing due to error');
    }
    app.log.info(`Got ${signal}! Shutting down gracefully`);
    await app.close();
  },
);

app.addHook('onClose', async () => {
  await closeListeners.uninstall();
});

await app.listen({ port, host });
```
I also tried callback version,
```
app.addHook('onClose', async (_, done) => {
  closeListeners.uninstall();
 done();
});
```
When `CTRL+C` is pressed, the server doesn't wait and close properly, instead it just hangs and I have to press `CTRL+C` twice.

<img width="1097" alt="image" src="https://github.com/mcollina/close-with-grace/assets/22151975/ba20382f-6961-458c-8f1c-d74f822fc54a">

**_The whole repo is [here](https://github.com/sujeet-agrahari/node-fastify-architecture) and can be cloned and tested locally._**

**Comment by mcollina** [comment]
Can you include a full repro?

**Comment by gkampitakis** [comment]
I see you start your server with `pnpm start` which in turn calls 

```sh
NODE_ENV=development nodemon --require=dotenv/config  src/server.js
```

You maybe need to configure nodemon to handle the signals ? This shouldn't happen when you start you server with `node src/server.js`.

**Comment by sujeet-agrahari** [comment]
I think it's `pnpm` issue, everything works fine with `npm`.

**Comment by sujeet-agrahari** [comment]
Yeah, this is a problem with `nodemon` itself. See here https://github.com/remy/nodemon/issues/2117

I ditched `nodemon` and using `node --watch` instead. 

Closing the issue as it's not related to this package, thanks.
