### ISSUE TITLE
Custom logger injection

### ISSUE THREAD

**Issue by bacebu4** [mcollina/close-with-grace#9]
Would be great if we could pass custom logger in options. This logger would implement interface of usual console.

Another improvement could be to pass logger to callback, example below

```js
closeWithGrace({ delay: 60_000, logger: new CustomLogger() }, async ({ err, logger }) => {
      if (err) {
        // logger is instance of CustomLogger
        logger.error('Got uncaught exception', err);
      }
      await db.close();
    });
``` 

I could make a PR for the feature

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by bacebu4** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Great, I'll make a PR for it
